---
# Which version of Magento to deploy
magento_version: 2.2.0

# These are the magento database settings
magento_db_name: magento 
magento_db_user: magento
magento_db_password: Pa$$w0rd
magento_db_remote_host: magento 

# You shouldn't need to change this.
mysql_port: 3306
mysql_host: magento

# This is used for the nginx server configuration, but # access to the
# magento site is not restricted by a # named host.
server_hostname: magento
mysql_root_password: Pa$$w0rd

# Magento Admin info
magento_admin_first: admin
magento_admin_last: lastname
magento_admin_email: admin@admin.com
magento_admin_user: admin
magento_admin_pass: 102030AA
magento_domain: http://{{ server_hostname }}/

#System handlers
group: magento
user: magento

#PHP-FPM sockets or TCP
php_listen: /var/run/php5-fpm.sock
