
- name: Instalação Nginx
  apt: name=nginx state=present update_cache=no

- name: Remover template padrão Nginx
  command: rm -f /etc/nginx/sites-enabled/default

- name: Copiar configuração vhost
  template: src=default dest=/etc/nginx/sites-available/{{ server_hostname }}

- name: Ativar novo vhost
  file: src=/etc/nginx/sites-available/{{ server_hostname }} dest=/etc/nginx/sites-enabled/{{ server_hostname }} state=link

- name: Iniciar nginx
  service: name=nginx state=restarted
