---
- name: Instalação Magento 
  remote_user: root
  hosts: magento
  sudo: true
  vars_files:
  - group_vars/all.yml

- name: Instalação MySQL
  hosts: db

  roles:
    - mysql

- name: Instalação nginx, PHP-FPM, Varnish, memcached
  hosts: web

  roles:
    - nginx
    - php-fpm
    - varnish
    - memcache
    - magento
