---

- name: EXCLUI Folder
  command: rm -rf /var/www/{{ server_hostname }}/

- name: Criar diretório MAGENTO
  command: mkdir -p /var/www/{{ server_hostname }}/

- name: Download MAGENTO
  get_url: url=https://github.com/magento-2/magento-2-community-sample-data/archive/2.2.0.tar.gz dest=/var/www/{{ server_hostname }}/2.2.0.tar.gz

- name: Descompactar 
  command: chdir=/var/www/{{ server_hostname }}/ tar xvf 2.2.0.tar.gz


- name: Mover MAGENTO para Root
  shell: chdir=/var/www/{{ server_hostname }}/ mv magento-2-community-sample-data-2.2.0/* .


- name: Criar {{ group }} grupo
  group: name={{ group }} state=present
  

- name: Adicionar usuário {{ user }}
  user: name={{ user }} group={{ group }} home=/var/www/{{ server_hostname }}

- name: Alteração de propriedade do MAGENTO installation 1
  file: path=/var/www/{{ server_hostname }}/ owner=www-data group=www-data state=directory recurse=yes

- name: Alteração de propriedade do MAGENTO installation 2
  shell: chdir=/var/www/{{ server_hostname }}/ find . -type f -exec chmod 644 {} \;

- name: Alteração de propriedade do MAGENTO installation 3
  shell: chdir=/var/www/{{ server_hostname }}/ find . -type d -exec chmod 755 {} \;

- name: Alteração de propriedade do MAGENTO installation 4
  shell: chdir=/var/www/{{ server_hostname }}/ chmod o+w var app/etc

- name: Alteração de propriedade do MAGENTO installation 5
  shell: chdir=/var/www/{{ server_hostname }}/ chmod 550 mage

- name: Alteração de propriedade do MAGENTO installation 6
  shell: chdir=/var/www/{{ server_hostname }}/ chmod -R o+w media

- name: Mage Setup
  shell: chdir=/var/www/{{ server_hostname }}/ ./mage mage-setup .
  
- name: Mage Estável
  shell: chdir=/var/www/{{ server_hostname }}/ ./mage config-set preferred_state stable

- name: Instalar Core
  shell: chdir=/var/www/{{ server_hostname }}/ ./mage install http://connect20.magentocommerce.com/community Mage_All_Latest --force

- name: Tornar mage executável
  shell: chmod +x /var/www/{{ server_hostname }}/mage

- name: Instalar PageCache via Varnish
  shell: chdir=/var/www/{{ server_hostname }} ./mage install http://connect20.magentocommerce.com/community Varnish_Cache --force

- name: Instalar Magento
  shell: chdir=/var/www/{{ server_hostname }}/ php -f install.php -- --license_agreement_accepted "yes" --locale "en_US" --timezone "Europe/London" --default_currency "GBP" --db_host "{{ mysql_host }}" --db_name "{{ magento_db_name }}" --db_user "{{ magento_db_user }}" --db_pass "{{ magento_db_password }}" --url "{{ magento_domain }}" --skip_url_validation --use_rewrites "yes" --use_secure "no" --secure_base_url "" --use_secure_admin "no" --admin_firstname "{{ magento_admin_first }}" --admin_lastname "{{ magento_admin_last }}" --admin_email "{{ magento_admin_email }}" --admin_username "{{ magento_admin_user }}" --admin_password "{{ magento_admin_pass }}"
  with_items: groups['db']

- name: Atualizar Index
  shell: chdir=/var/www/{{ server_hostname }}/ php -f shell/indexer.php reindexall
  
- name: Remover arquivos TAR
  shell: chdir=/var/www/{{ server_hostname }}/ rm -rf magento-{{ magento_version }}.tar.gz magento-sample-data-1.6.1.0.tar.gz

- name: Remover arquivos txt SQL
  shell: chdir=/var/www/{{ server_hostname }}/ rm -rf *.sample *.txt data.sql

- name: Remover diretório Magento
  shell: chdir=/var/www/{{ server_hostname }}/ rm -rf magento/ magento-sample-data-1.6.1.0/
  
- name: Reiniciar nginx
  service: name=nginx state=restarted

- name: Reiniciar php-fpm
  service: name=php5-fpm state=restarted

- name: Reiniciar Varnish
  service: name=varnish state=restarted   
