
---

- name: Instalar Varnish
  apt: name=varnish state=present
  
- name: Copiar configurações varnish
  template: src=varnish dest=/etc/default/varnish

- name: Copiar configurações vcl varnish
  template: src=default.vcl dest=/etc/varnish/default.vcl

- name: Inicializar varnish
  service: name=varnish state=started enabled=yes
