#---
- name: Instalação Mysql
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - mysql-server
   - mysql-client
   - python-mysqldb

- name: copy .my.cnf file with root password credentials
  template: src=root.my dest=/root/.my.cnf owner=root mode=0600

- name: MySQL | Remover teste MySQL
  mysql_db: db=test state=absent 

- name: Deletar usuário anônimo MySQL
  mysql_user: name="" state="absent" 

- name: Criar banco de dados {{magento_db_name}}
  mysql_db: name={{magento_db_name}} state=present

- name: Criar usuário {{ magento_db_user }}
  mysql_user: name={{ magento_db_user }} password={{ magento_db_password }}  priv={{ magento_db_name }}.*:ALL host={{ magento_db_remote_host }} state=present
