---
# tasks file for php

- name: Install php and deps
  apt: name={{ item }} state=present
  with_items:
    - php56
    - php56-xml
    - php56-pdo
    - php56-mbstring
    - php56-mysqlnd
    - php56-gd
    - php56-mcrypt
    - php56-soap
    - mod24_ssl
    - vim
